---
title: "ica-uni"
format: html
---


```{r}
library(ggplot2)
library(tidyverse)
# Import data
hikes <- read.csv("https://mac-stat.github.io/data/high_peaks.csv")

ggplot(hikes, aes(x = rating))
```

```{r}
# Add a bar plot LAYER
ggplot(hikes, aes(x = rating)) +
  geom_bar()
```

```{r}
# Add meaningful axis labels
ggplot(hikes, aes(x = rating)) +
  geom_bar() +
  labs(x = "Rating", y = "Number of hikes")
```

```{r}
# FILL the bars with blue
ggplot(hikes, aes(x = rating)) +
  geom_bar(fill = "blue") +
  labs(x = "Rating", y = "Number of hikes")
```

```{r}
# COLOR the outline of the bars in orange
ggplot(hikes, aes(x = rating)) +
  geom_bar(color = "orange", fill = "blue") +
  labs(x = "Rating", y = "Number of hikes")
```

```{r}
# Change the theme to a white background
ggplot(hikes, aes(x = rating)) +
  geom_bar(color = "orange", fill = "blue")  +
  labs(x = "Rating", y = "Number of hikes") + 
  theme_minimal()
```

```{r}
ggplot(hikes, aes(x = elevation)) + 
  geom_bar()
```

```{r}
# Add a histogram layer
ggplot(hikes, aes(x = elevation)) +
  geom_histogram()
```

```{r}
# Fill the bars in blue
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white", fill = "blue") 
```

```{r}
# Change the width of the bins to 200 feet
ggplot(hikes, aes(x = elevation)) +
  geom_histogram(color = "white", binwidth = 200) +
  labs(x = "Elevation (feet)", y = "Number of hikes")
```

```{r}
ggplot(hikes, aes(x = elevation)) +
 geom_density(color = "blue", fill = "orange")
```

